### ISSUE TITLE
HTTP Origin header didn't match request.base_url when signing up on a Danbooru instance

### ISSUE THREAD

**Issue by AxelTerizaki** [danbooru/danbooru#5524]
Hello.

I've been trying to setup a public Danbooru using the docker installation and while it works, signing up as a new user is impossible.

Once you fill the sign up form, you get the following error message 👍 

`Error: HTTP Origin header (https://xxx) didn't match request.base_url (http://xxx)`

Obviously, something in the config is thinking that the base_url is http only for some reason. I see that in the default_config.rb file in the source code : 

```ruby
    def canonical_url
      "http://#{Danbooru.config.hostname}"
    end
```

For some reason my environment variables are ignored.

Here's my docker_compose.yml

```yaml
# A Docker Compose file that launches a minimal Danbooru instance. This is
# suitable as a quick demo or for personal use, not for public-facing sites.
#
# This will start a Danbooru instance running on http://localhost:3000.
#
# Usage:
#
#  docker-compose up
#  docker-compose down
#
# References:
#
# * https://docs.docker.com/get-docker/
# * https://docs.docker.com/compose/install/
# * https://docs.docker.com/compose/compose-file/compose-versioning
# * https://docs.docker.com/compose/release-notes

# Version 3.4 is the latest version that is supported by the version of Docker
# Compose shipped with Ubuntu 18.04 LTS (version 1.17.4).
version: "3.4"

name: danbooru

x-base-template: &base-template
  user: root
  pull_policy: always # Uncomment this to always pull the latest image when deploying.
  image: ghcr.io/danbooru/danbooru:master # you can change this to danbooru:master to get the latest upstream changes
  environment:
    RAILS_ENV: production # Set this to development to force danbooru to freshly compile js/css assets (for example if you're doing local development)
    RAILS_SERVE_STATIC_FILES: true
    PUMA_WORKERS: 1
    DATABASE_URL: postgresql://danbooru@postgres/danbooru
    DANBOORU_APP_NAME: xxx
    DANBOORU_REDIS_URL: redis://redis:6379
    DANBOORU_IQDB_URL: http://iqdb:5588
    # DANBOORU_CANONICAL_URL: http://localhost:3000
    # # If you want to host danbooru under your own domain you need to replace the above line with the following (replace with your actual domain):
    DANBOORU_CANONICAL_URL: https://xxx
    DANBOORU_HOSTNAME: xxx
    DANBOORU_CONTACT_EMAIL: xxx@xxx.xxx
    DANBOORU_NEW_USER_VERFICATION: false
    DANBOORU_USER_UPGRADES_ENABLED: false

  volumes:
    - "/var/danbooru/data/images:/danbooru/public/data"
    # # If you want to do local development you can uncomment these lines to force the container to use your local changes
    # # Simply replace $HOME/danbooru to where you cloned the repo
    # - "$HOME/danbooru/app:/danbooru/app"
    # - "/var/danbooru/data/config:/danbooru/config"
    # - "$HOME/danbooru/db:/danbooru/db"
    # - "$HOME/danbooru/test:/danbooru/test"

services:
  danbooru:
    <<: *base-template
    ports:
      - "5000:3000"
    tmpfs:
      - /tmp
    depends_on:
      - postgres
    restart: always
    command: ["bash", "-c", "bin/rails db:prepare && bin/rails db:seed && bin/rails server -b 0.0.0.0"]

  cron:
    <<: *base-template
    depends_on:
      - danbooru
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/rails danbooru:cron"]

  jobs:
    <<: *base-template
    depends_on:
      - danbooru
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/good_job start"]

  # https://github.com/danbooru/iqdb
  # https://hub.docker.com/repository/docker/evazion/iqdb
  iqdb:
    image: evazion/iqdb
    volumes:
      - "/var/danbooru/data/iqdb:/iqdb/data"
    command: ["http", "0.0.0.0", "5588", "/iqdb/data/iqdb.sqlite"]

  redis:
    image: redis

  postgres:
    image: evazion/postgres
    environment:
      POSTGRES_USER: danbooru
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "/var/danbooru/data/db:/var/lib/postgresql/data"

#volumes:
#  danbooru-images:
#    name: danbooru-images
#  danbooru-data:
#    name: danbooru-data
#  iqdb-data:
#    name: iqdb-data
```

Any idea what I am missing?

Thanks in advance

**Comment by OhGodItsBroken** [comment]
I had this issue, and I had to make sure my apache conf had these lines to fix the header.
`    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}`

And I enabled the header mod.

`a2enmod header`

It fixed this specific error for me at least. I know NGINX has similar but different syntax if that's what you're using.

**Comment by helpimnotdrowning** [comment]
It's not ignoring your env, you've just forgotten to set some headers for whatever webserver you're using.

In nginx, I set my config like this:

```nginx
server {
    listen 80;
    server_name danbooru.yourdomain.com;
    client_max_body_size 100M; # danbooru default max upload size, if you dont set this the client gets 413'd

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $Host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by KenwoodFox** [comment]
I'm using Caddy as my RP and im having trouble with this, what headers do i need to forward? And do i need to do anything on the other end with nginx?

```
# DanBooru Server
booru.kitsunehosting.net {
        reverse_proxy http://10.85.3.71:3000 {
                header_up X-Forwarded-Proto {request_scheme}
                header_up X-Forwarded-SSL https
                header_up X-Real-IP {remote_host}
        }
}
```

**Comment by KenwoodFox** [comment]
> See the example config in [config/nginx.conf](https://github.com/danbooru/danbooru/blob/751297da486743cc9d92a81ff310d9860d0c4185/config/nginx.conf#L66-L90). In Nginx syntax, the headers you need to set are:
> 
> ```
> proxy_set_header X-Forwarded-For $remote_addr;
> proxy_set_header X-Forwarded-Host $http_host;
> proxy_set_header X-Forwarded-Port $server_port;
> proxy_set_header X-Forwarded-Proto $scheme;
> proxy_set_header Host $http_host;
> ```
> 
> I think Caddy sets these automatically, so you shouldn't have to add them yourself.
> 
> If you're using the [Docker guide](https://github.com/danbooru/danbooru/wiki/Docker-Guide) to run Danbooru, then you have to set `DANBOORU_REVERSE_PROXY=true` in `.env.local` to tell it there's a reverse proxy in front of your instance and to trust the `X-Forwarded-*` headers you're sending it.
> 
> If you're still having trouble, you can do `http://localhost:3000/nginx/headers` or `http://localhost:3000/status.json` to see which headers are actually being received by your instance (replace `localhost:3000` with your actual server). Compare this with [danbooru.donmai.us/nginx/headers](https://danbooru.donmai.us/nginx/headers) to see what it should look like on a real instance. The `X-Forwarded-*` headers are what matters.
> 
> Lastly, you can check that your proxy is forwarding the `Origin` header correctly. You can check this by doing `curl -X POST -H "Origin: http://localhost:3000" https://localhost:3000/nginx/headers` (replacing `localhost:3000` with your actual server) and checking that the Origin header matches the Host header. If they don't match, then your proxy isn't forwarding the Origin header correctly and it's the source of this error.

This was really comprehensive and I'm sad it didn't seem to work for me! I appreciate how much detail and how many different options you included though. 

I removed my manual headers from caddy after testing your command to curl the headers from my server, it looks like it makes sense, here's with my headers
```
...
Origin: https://booru.mydomain.net
X-Forwarded-For: <IP>
X-Forwarded-Host: booru.mydomain.net
X-Forwarded-Proto: {request_scheme}
X-Forwarded-Ssl: https
X-Real-Ip: <IP>
```

and without
```
...
Origin: https://booru.mydomain.net
X-Forwarded-For: <IP>
X-Forwarded-Host: booru.mydomain.net
X-Forwarded-Proto: https
```

Since I'm asking for help maybe i should make a new issue?

I added the env variable to my env file but i previously had an empty environment file, should i configure it in `config/danbooru_local_config.rb` as well or is env better?

Thanks again so much

**Comment by KenwoodFox** [comment]
So, i saw this line in the config file default
https://github.com/danbooru/danbooru/blob/751297da486743cc9d92a81ff310d9860d0c4185/config/danbooru_default_config.rb#L77-L78

Does this mean that the connection from RP -> Danbooru needs to be https? because i have not set it up for that. danbooru is running in HTTP, and im proxying it, turning it into https at the front. Maybe that's whats confusing? i tried setting the env variable for proxy mode but how can i check that it actually stuck? im not confident it did if i set my canonical URL to include https and its still expecting HTTP...

**Comment by evazion** [comment]
Try it again, I just realized that ae3569780 wasn't on the production branch yet, so if you were using `docker compose up` it wouldn't work. It should work now.

Also make sure the `Host` header is the same as `X-Forwarded-Host`.

>I added the env variable to my env file but i previously had an empty environment file, should i configure it in config/danbooru_local_config.rb as well or is env better?

`DANBOORU_REVERSE_PROXY=true` should go in `.env.local`. It can't go in `danbooru_local_config.rb` because it has to be defined as an environment variable to take effect in `config/nginx.conf`.

>Does this mean that the connection from RP -> Danbooru needs to be https?

No, the RP -> Danbooru connection should be HTTP. It won't work if you try to make it HTTPS. That line is just saying that if you set your canonical URL to `https://booru.mydomain.net`, then don't try to access your site with `http://booru.mydomain.net` or `http://localhost:3000` instead because it won't work.

>i tried setting the env variable for proxy mode but how can i check that it actually stuck

You can compare `https://booru.mydomain.net/nginx/headers` with `https://booru.mydomain.net/status.json`. If the `X-Forwarded-*` headers are the same, that means reverse proxy mode is working. If they're different, that means we're ignoring the `X-Forwarded-*` headers sent by your reverse proxy because DANBOORU_REVERSE_PROXY isn't enabled.

**Comment by KenwoodFox** [comment]
Funny enough I was using `docker compose up` thanks for merging that in, I cloned down and pulled the new image.

Heres my comparison with the headers and status, status json looks like this
![image](https://github.com/danbooru/danbooru/assets/31870999/51e4c22b-4097-4e71-92de-478c353a8008)

and my headers include this:
```
X-Forwarded-For: 162.158.154.39
X-Forwarded-Host: booru.mydomain.net
X-Forwarded-Proto: https
```

so clearly that X-Forwarded-Proto is messing up? I checked and in the root folder (not in config) I've got my `.env.local` and it has `DANBOORU_REVERSE_PROXY=true` so, i think that's the problem but im not sure why exactly. the configs section of my docker compose is unmodified it still points to .env.local

Thanks again for being so verbose and detailed with your response, it really helps me go through each one and verify. I think that the root of my issue is simply reverse proxy just, not being enabled.

**Comment by KenwoodFox** [comment]
Ah! it works! so sorry for all the back and forth, I made it look exactly like this, with quotes around true and it worked
```
$ cat .env.local 
export DANBOORU_REVERSE_PROXY="true"
```

Thank you!

**Comment by KenwoodFox** [comment]
Sorry to bump an old issue, still having this issue!

![image](https://github.com/danbooru/danbooru/assets/31870999/40c019bc-65c0-4e86-9ae3-b0be748d3f49)

I spent some time looking thru the old comments and no matter what i do i cant get `Host` to match the regular `https://`

If i change the header to like `Host = https://booru.mydomain.com` it comes up silly like this

![image](https://github.com/danbooru/danbooru/assets/31870999/f3bd2cd7-1bc9-4f4e-884d-31ae8e2e7fc1)

I know, at this point its not really a booru problem. Because clearly it works for everybody else, and it must be something I've setup wrong or misconfigured in my reverse proxy. But pointers like the instructions you gave for matching/checking headers would be appreciated! When i figure it out I'll be sure to submit a doc blurb back

**Comment by nonamethanks** [comment]
Assuming this was fixed. Reopen if it happens again.
